name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
      with:
        version: 10.28.0

    - name: Setup Node.js
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
      with:
        node-version: 22.22.1
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
