name: checkout-sheet-kit-react-native

dev.edition: 2024

type: node

up:
  - packages:
      - swiftlint
      - ccache
  - ruby
  - xcode:
      version: '26.0'
      runtimes:
        ios:
          - '26.0'
  - node:
      version: v20.11.1
      yarn: 1.22.22
  - custom:
      name: Install NPM dependencies
      met?: ls -l | grep node_modules
      meet: |
        yarn
  - custom:
      name: Generate iOS xcconfig from env
      met?:
        test -f sample/ios/JSEnvironment.xcconfig && test sample/.env -ot
        sample/ios/JSEnvironment.xcconfig
      meet: |
        yarn env-to-xcconfig
  - custom:
      name: Install gems
      met?: (cd sample/ios && bundle check)
      meet: |
        (cd sample/ios && bundle install)
  - custom:
      name: Install pods
      met?: (cd sample/ios && bundle exec pod check --ignore-dev-pods)
      meet: |
        yarn pod-install
  - custom:
      name: Build node module
      met?: (cd modules/@shopify/checkout-sheet-kit && ls -l | grep lib)
      meet: |
        yarn module build

check:
  lint_swift: ./scripts/lint_swift
  lint_module: yarn module lint
  lint_sample: yarn sample lint

commands:
  build:
    desc: Builds the Typescript and Android package for local development
    run: |
      yarn module build
      ./scripts/publish_android_snapshot ~/src/github.com/Shopify/checkout-sheet-kit-android 4.0.0-SNAPSHOT

  server:
    desc: 'Start development server'
    run: yarn sample start --reset-cache

  ios:
    desc: 'Run iOS simulator'
    run: yarn sample ios

  android:
    desc: 'Run Android emulator'
    run: yarn sample android

  clean:
    desc: 'rm -rf all generated directories'
    run: |
      yarn module clean
      yarn sample clean
      yarn clean
      if command -v ccache >/dev/null 2>&1; then
        ccache -C
      fi
      echo "✅ Cleaned root, module and sample workspaces"

  fix:
    desc: Fix linting
    run: |
      ./scripts/lint_swift fix
