name: Setup iOS Simulator
description: Configure iOS Simulator for testing

runs:
  using: composite
  steps:
    - name: Setup iOS Simulator
      shell: bash
      run: |
        xcode-select -p
        xcrun xcodebuild -version
        xcrun simctl list runtimes
        xcrun simctl list devicetypes
        xcrun simctl delete all
        CURRENT_SIMULATOR_UUID=$(xcrun simctl create TestDevice "iPhone 15 Pro")
        echo "CURRENT_SIMULATOR_UUID=$CURRENT_SIMULATOR_UUID" >> $GITHUB_ENV
