name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Cache turbo build setup
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-
