# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '16.6'

prepare_react_native_project!

# Suppress warnings in dependencies when building the sample app
inhibit_all_warnings!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ReactNative' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => true
  )

  target 'ReactNativeTests' do
    inherit! :complete
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    # Enable ccache by default - controlled via build script PATH manipulation
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )

    # WORKAROUND
    # This fixes issues with the 'React-Core-AccessibilityResources' dependency when archiving the sample app in XCode:
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end

      if target.name == "React-Core-RCTI18nStrings"
        target.remove_from_project
      end
    end
  end
end

pod "RNShopifyCheckoutSheetKit", :path => "../../modules/@shopify/checkout-sheet-kit"
pod "ShopifyCheckoutSheetKit", :path => "~/src/github.com/Shopify/checkout-sheet-kit-swift"
pod "ShopifyCheckoutSheetKit/AcceleratedCheckouts", :path => "~/src/github.com/Shopify/checkout-sheet-kit-swift"
