source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '1.16.1'
gem 'cocoapods-check', '1.1.0'
gem 'activesupport', '>= 6.1.7.5', '< 7.3.0'
