/*
MIT License

Copyright 2023 - Present, Shopify Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#import <React/RCTBridgeModule.h>
#import <React/RCTViewManager.h>
#import <RNShopifyCheckoutSheetKitSpec/RNShopifyCheckoutSheetKitSpec.h>

// Registers the Swift module class (ShopifyCheckoutSheetKit.swift) with the RN
// runtime under the name 'RCTShopifyCheckoutSheetKit', extending the codegen
// base class so TurboModule dispatch can find it.
//
// Method declarations (`RCT_EXTERN_METHOD`) are intentionally absent for most
// methods: the codegen-generated `NativeShopifyCheckoutSheetKitSpecJSI` invokes
// each method via its `@objc` selector directly (see ShopifyCheckoutSheetKit.swift).
// `setConfig` is declared so ObjCTurboModule sees the Swift selector's
// NSDictionary argument and does not apply codegen's C++ struct conversion before
// invoking Swift.
@interface RCT_EXTERN_MODULE (RCTShopifyCheckoutSheetKit, NativeShopifyCheckoutSheetKitSpecBase)

RCT_EXTERN_METHOD(setConfig:(NSDictionary *)configuration)

@end

// TurboModule registration. `RCTModuleProviders` (generated by codegen from
// `package.json → codegenConfig.ios.modulesProvider`) looks up classes that
// `respondsToSelector:@selector(getTurboModule:)`. Without this category,
// our Swift class would not appear in the providers map and JS calls would
// fall back to the legacy bridge — which has no methods declared here and
// no sync support.
@interface RCTShopifyCheckoutSheetKit (TurboModule) <RCTTurboModule>
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params;
@end

@implementation RCTShopifyCheckoutSheetKit (TurboModule)
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return std::make_shared<facebook::react::NativeShopifyCheckoutSheetKitSpecJSI>(
      params);
}
@end

/**
 * AcceleratedCheckoutButtons View Manager
 */
@interface RCT_EXTERN_MODULE (RCTAcceleratedCheckoutButtonsManager, RCTViewManager)

/**
 * Unified checkout identifier payload.
 * Accepts either { cartId } or { variantId, quantity }.
 */
RCT_EXPORT_VIEW_PROPERTY(checkoutIdentifier, NSDictionary*)

/**
 * Corner radius for rendered buttons, in points. Defaults to 8.
 */
RCT_EXPORT_VIEW_PROPERTY(cornerRadius, NSNumber*)

/**
 * Wallets to render. Accepts an array of identifiers such as "shopPay" and "applePay".
 * If omitted, native defaults are used.
 */
RCT_EXPORT_VIEW_PROPERTY(wallets, NSArray*)

/**
 * Label variant for the Apple Pay button (e.g., "plain", "buy", "checkout").
 */
RCT_EXPORT_VIEW_PROPERTY(applePayLabel, NSString*)

/**
 * Style variant for the Apple Pay button (e.g., "automatic", "black", "white", "whiteOutline").
 */
RCT_EXPORT_VIEW_PROPERTY(applePayStyle, NSString*)

/**
 * Emitted when checkout fails. Payload contains a CheckoutException-like shape.
 */
RCT_EXPORT_VIEW_PROPERTY(onFail, RCTBubblingEventBlock)

/**
 * Emitted when checkout completes successfully. Payload contains order details.
 */
RCT_EXPORT_VIEW_PROPERTY(onComplete, RCTBubblingEventBlock)

/**
 * Emitted when checkout is cancelled by the buyer.
 */
RCT_EXPORT_VIEW_PROPERTY(onCancel, RCTBubblingEventBlock)

/**
 * Emitted when the native render state changes. Values: "loading", "rendered", "error".
 */
RCT_EXPORT_VIEW_PROPERTY(onRenderStateChange, RCTBubblingEventBlock)

/**
 * Direct event used to determine whether native should attempt recovery from an error.
 */
RCT_EXPORT_VIEW_PROPERTY(onShouldRecoverFromError, RCTDirectEventBlock)

/**
 * Emitted when a web pixel event occurs during checkout.
 */
RCT_EXPORT_VIEW_PROPERTY(onWebPixelEvent, RCTBubblingEventBlock)

/**
 * Emitted when a link is clicked within the checkout experience. Payload contains the URL.
 */
RCT_EXPORT_VIEW_PROPERTY(onClickLink, RCTBubblingEventBlock)

/**
 * Emitted when the intrinsic height of the native view changes. Payload contains { height }.
 */
RCT_EXPORT_VIEW_PROPERTY(onSizeChange, RCTDirectEventBlock)

@end
