#!/bin/bash

FILENAME="modules/@shopify/checkout-sheet-kit/package.snapshot.json"
TMP_SNAPSHOT_FILENAME="snapshot.json"

# Set up some colors to use later
red=$(tput setaf 1)
green=$(tput setaf 2)
reset=$(tput sgr0)

./scripts/create_snapshot $TMP_SNAPSHOT_FILENAME

if [ $? -ne 0 ]; then
  echo "${red}Failed to create snapshot.${reset}"
  exit 1
fi

diff $FILENAME $TMP_SNAPSHOT_FILENAME &>/dev/null

if [ $? -eq 0 ]
then
    echo "${green}SUCCESS${reset}: The package files have not changed."
else
    echo "

    ${red}ERROR${reset}: The package files have changed.

    If this is intentional, run \"yarn snapshot\" at the root of this repo to update the \"$FILENAME\" file.

    If it NOT intentional, please manually check the diff below to discern if the file(s) should be included in the public package or not:


${green}EXISTING SNAPSHOT${reset}                                                      ${red}NEW SNAPSHOT${reset}
    "
    diff --color --side-by-side $FILENAME $TMP_SNAPSHOT_FILENAME

    exit 1
fi

rm $TMP_SNAPSHOT_FILENAME
