#!/bin/bash

OUTPUT_FILE=${1:-modules/@shopify/checkout-sheet-kit/package.snapshot.json}

(cd modules/@shopify/checkout-sheet-kit && npm pack --dry-run --json) | jq ".[0].files | map(.path)" > $OUTPUT_FILE
