name: Cocoapods
description: Install cocoapods for sample app

runs:
  using: composite
  steps:
    - name: Cache cocoapods
      id: cache-cocoapods
      uses: actions/cache@e12d46a63a90f2fae62d114769bbf2a179198b5c # v3.3.3
      with:
        path: |
          **/ios/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('sample/ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-cocoapods-

    - name: Install cocoapods
      if: steps.cocoapods-cache.outputs.cache-hit != 'true'
      shell: bash
      env:
        NO_FLIPPER: "1"
      run: |
        ROOT=$(pwd)
        cd sample
        bundle install
        cd ios
        NO_FLIPPER=1 bundle exec pod install
        cd $ROOT
