name: Cocoapods
description: Install cocoapods for sample app

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1.255.0
      with:
        ruby-version: 3.3.6
        bundler-cache: true
        working-directory: sample

    - name: Cache cocoapods
      id: cache-cocoapods
      uses: actions/cache@v4
      with:
        path: |
          sample/ios/Pods
        key: ${{ runner.os }}-cocoapods-${{ hashFiles('sample/ios/Podfile.lock', 'sample/Gemfile.lock', 'sample/Gemfile', 'package.json', 'sample/package.json', 'modules/@shopify/checkout-sheet-kit/package.json', 'yarn.lock') }}

    - name: Install cocoapods
      shell: bash
      run: |
        set -euo pipefail
        ROOT=$(pwd)
        cd sample
        bundle install
        cd ios
        bundle exec pod install --deployment --repo-update
        cd $ROOT
