name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  react:
    runs-on: shopify-ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup

      - name: Typecheck + ESLint
        run: yarn lint

  swift:
    runs-on: shopify-ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict

      - name: Check License Headers
        run: ./scripts/copy_license && git diff --name-only --exit-code
